### PR TITLE
Bump to v0.6.0

### PR DESCRIPTION
**Pull request by klausenbusk**

### CODE REVIEW

**Comment by dghubble** [comment]
Testing this out...

**Comment by dghubble** [comment]
The `vlan` plugin is the only one not copied over, let's include it too. Dockerfile: `ADD dist/vlan /opt/cni/bin/vlan`.

**Comment by klausenbusk** [comment]
> The vlan plugin is the only one not copied over, let's include it too. Dockerfile: ADD dist/vlan /opt/cni/bin/vlan.

Fixed, is there any reason why we copy every binary individually? I just replaced all the `ADD` lines in the `Dockerfile` with:
```
ADD dist/ /opt/cni/bin/
```
Is there any issue with that approach?

**Comment by dghubble** [comment]
Believe this includes `sample` now

**Comment by klausenbusk** [comment]
> Believe this includes sample now

I think it is more clean to remove it afterwards (?) (less lines), I just tried changing the `Dockerfile` so it use Docker new [`multi-stage` feature](https://docs.docker.com/engine/userguide/eng-image/multistage-build/#use-multi-stage-builds), it make `build-image.sh` less important.

**Comment by dghubble** [comment]
We don't need all these changes in this PR. The goal is to bump the CNI version and just not forget the `vlan` plugin. Changing the base image and build process shouldn't happen here. Can you revert back toward the original please.

**Comment by dghubble** [comment]
Thanks!

**Comment by klausenbusk** [comment]
I have opened a new PR with the build changes: https://github.com/coreos/flannel-cni/pull/7

**Pull request merged**
